//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HairCut.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Slider : Image
    {
        public int SliderId { get; set; }
        public string Heading { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string ImgPath { get; set; }
    }
}
